### ISSUE TITLE
`file-printf-prepend` out of memory 

### ISSUE THREAD

**Issue by bernhardmgruber** [shrpnsld/amalgamate#2]
Hi! I tried to amalgamate the [alpaka](https://github.com/alpaka-group/alpaka) library using your script, but it runs out of memory. Specifically the following line of code just allocates endlessly (up to ~33GiB on my machine) and is then killed by the OS (in my case Ubuntu 23.04):

https://github.com/shrpnsld/amalgamate/blob/1e43e6629f5421a8011bba96da3d9bcc58984ded/amalgamate#L677

If I use a simpler statement like:
```bash
before=$(cat "$file_path")
printf "$format%s" "${arguments[@]}" "$before" > "$file_path"
```
the script runs successfully.

I run `amalgamate -o . -H -v -a -n 'alpaka'` inside the `include/alpaka` directory of my working copy.

Could you please have a look? Thank you!

**Comment by shrpnsld** [comment]
Hello Bernhard! Thank you for trying out my script!
I've checked out the problem you've described, and could reproduce it locally with alpaka source code.
Thank you for pointing out the problem code and sending me PR. I've suggested a bit different solution though. Let me know if you have any questions, corrections or suggestions.

**Comment by bernhardmgruber** [comment]
Thanks a lot for the help! I love your script :) It's running in my CI for some years already to provide a [single header](https://github.com/alpaka-group/llama#single-header).

The issue is solved for me now, thanks!

**Comment by shrpnsld** [comment]
I'm glad your making a use out of it! Feel free to ask for a help or a feature :)

Also I would warn not to set output path to be the same as source path (as I've seen in your way of calling script). This may cause output files to be amalgamated to themselves infinitely. I don't have any checks (yet) that prevent script from doing this.
