### ISSUE TITLE
amalgamate error: unknown file extension

### ISSUE THREAD

**Issue by bernhardmgruber** [shrpnsld/amalgamate#4]
Hi, your recent commit https://github.com/shrpnsld/amalgamate/commit/b0d5cb79891a1da6204d141c22907609bca1dbed broke our workflow, where we basically run this script as part of our CI: https://github.com/alpaka-group/alpaka/blob/develop/script/create-single-header.sh. At its heart, there is this call:

```
amalgamate -o $tmp_dir -v -a -n 'alpaka' -I $workingcopy_dir/include -- $workingcopy_dir/include/alpaka/alpaka.hpp
```
Which works fine before the offending commit. Afterwards, we get the following error:
```
amalgamate error: unknown file extension "/home/bgruber/dev/alpaka/script/../include/alpaka/alpaka.hpp"
```
I think the problem is the changes to the list of header file extensions here: https://github.com/shrpnsld/amalgamate/commit/b0d5cb79891a1da6204d141c22907609bca1dbed#diff-bd39db4c004fb1b4cdd7cd6390f7aa4c22aec3ec3210b901b3766da9b65d5e50L30-R33
If I change `(h,hh,hpp,hxx,h++,tpp,txx,tpl,ii,ixx,ipp,inl)` into `(h hh hpp hxx h++ tpp txx tpl ii ixx ipp inl)` again, my workflow completes successfully.

We would be really happy if you could have a look at this! Thank you for the great work!

**Comment by shrpnsld** [comment]
Thank you for informing about the issue. Sorry about that.
Fixed this one and also another one that was causing input directory being added as a file to be amalgamated. Please check this [PR for the fix](https://github.com/shrpnsld/amalgamate/pull/5).
Tested it with my project, your project with options you've specified and it seems to work without an issues. If everything is working for you also, I'm ready to merge it.

**Comment by bernhardmgruber** [comment]
Thanks for the fast response! Your PR fixes our issues downstream. Great job!

**Comment by shrpnsld** [comment]
Thank you too! Merged fix into master.
